### ISSUE TITLE
Kirby-code-editor seems to make the field translation unreliable

### ISSUE THREAD

**Issue by marcomezzavilla** [sylvainjule/kirby-code-editor#2] opened 2021-07-09 10:57 UTC
```json
Kirby 3.5.3.1
kirby-code editor: 1.0.0
```

—

I'm using this plugin to allow editors to insert the embed code of an externally managed contact form.
The website has two languages, but switching the language from the panel the field often doesn't change unless you refresh the page.

This can cause problems because if you save the page with the field in the wrong language, the translations are continuously overwritten.

Changing the field type to a normal `textarea` solves the problem.

**Comment by sylvainjule** [comment] 2021-11-19 12:24
Apologies for the delay. Is this still happening with 3.6?

I cannot reproduce with 3.5.3 in my test environment, everything translates correctly. 3.6 also works fine here.

**Comment by sylvainjule** [comment] 2022-02-23 15:53
Closing this, please don't hesitate to reopen if the issue still occurs.

**Closed by sylvainjule** 2022-02-23 15:53 UTC
Labels: bug, needs: information
